version: '3.8'  # Use the appropriate version for your needs

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      CASSANDRA_HOST: cassandra
    depends_on:
      - cassandra
    networks:
      - group3_network

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - todo-cassandra-data:/var/lib/cassandra
    networks:
      - group3_network

networks:
  group3_network:

volumes:
  todo-cassandra-data:
